platform :ios, '6.0'
pod 'ReactiveCocoa'
pod 'pop', '~> 1.0.7'
pod 'AFNetworking', '~> 2.5.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'TMCache', '~> 1.2.3'
pod 'FMDB', '~> 2.4'
pod 'shareSDK', '~> 0.0.2'
pod 'FXBlurView', '~> 1.6.3'
pod 'IQKeyboardManager', '~> 3.2.0.3'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MJRefresh', '~> 1.0.0'
pod 'MJExtension', '~> 1.0.0'
pod 'ReactiveCocoa', '~> 1.0.0'
